# Generated by Django 2.2.3 on 2019-07-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
